version: "3.7"

services:

  # Requires the build of the stubs first
  grpc-server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      envoymesh:
        aliases:
          - kv-backend-service

  grpc-server-proxy:
    build:
      context: .
      dockerfile: Dockerfile-server
    networks:
      envoymesh:
        aliases:
          - kv-backend-proxy
    ports:
      - "8811:8811"

  grpc-client-proxy:
    build:
      context: .
      dockerfile: Dockerfile-client
    networks:
      envoymesh:
        aliases:
          - kv-client-proxy
    ports:
      - "9911:9911"

networks:
  envoymesh: {}
