version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    networks:
      - envoymesh
    ports:
      - "8087:8000"

  ext_authz-http-service:
    build:
      context: .
      dockerfile: Dockerfile-http-auth-service
    networks:
      - envoymesh
  demo-service-1:
    build:
      context: .
      dockerfile: Dockerfile-demo-service1
    volumes:
      - ./demo-service1/service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      - envoymesh
    ports:
      - "8085:8000"
    environment:
      - SERVICE_NAME=1

networks:
  envoymesh: {}
