version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    networks:
      - envoymesh
    ports:
      - "8087:8080"
      - "8001:8001"

  demo-service:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      - envoymesh
    ports:
      - "8085:8000"
    environment:
      - SERVICE_NAME=1

networks:
  envoymesh: {}
