FROM envoyproxy/envoy:v1.18-latest

COPY ./server/envoy-proxy.yaml /etc/server-envoy-proxy.yaml
COPY ./server/address.pb /etc/address.pb
RUN chmod go+r /etc/server-envoy-proxy.yaml
CMD ["/usr/local/bin/envoy", "-c", "/etc/server-envoy-proxy.yaml", "--service-cluster", "backend-proxy"]
