apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: petstore
  name: petstore
spec:
  replicas: 1
  selector:
    app: petstore
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petstore
    spec:
      containers:
      - image: docker.io/sreddyku/envoy-proxy-grpc-json:1.0
        imagePullPolicy: Always
        name: envoy
        ports:
        - containerPort: 8811
          protocol: TCP
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      - image: docker.io/sreddyku/grpc-test-service:1.0.0
        imagePullPolicy: Always
        name: petstore
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange

---

#########################
##       SERVICE       ##
#########################
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petstore
  name: petstore
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-10000
    port: 80
    protocol: TCP
    targetPort: 8811
  selector:
    app: petstore
  sessionAffinity: None
  type: LoadBalancer
